### ISSUE TITLE
Missing a license

### ISSUE THREAD

**Issue by tv42** [brhoades/adaptive-backoff#1]
Hi. I was looking for a tiny backoff library, and stumbled on this.
[Cargo.toml](https://github.com/brhoades/adaptive-backoff/blob/f879bcec4274654355e0ef6cd4d353c5f88ee8a7/Cargo.toml#L6) seems to intend for this to be MIT licensed, but could you add a proper license file, please?

**Comment by brhoades** [comment]
Sorry about that. Done.
