### ISSUE TITLE
Unnecessary dependency on pretty_env_logger

### ISSUE THREAD

**Issue by tv42** [brhoades/adaptive-backoff#2]
Hi. Me again ;-)

The dependency on pretty_env_logger doesn't seem to be used anywhere.

https://github.com/brhoades/adaptive-backoff/blob/b6bdb9929fef8ded939285e7f55e595b62d23535/Cargo.toml#L19

**Comment by brhoades** [comment]
Ah yeah, I dropped multiple dependencies in 0.2 and this one slipped through. Thanks!
